name: pr

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Code build, lint and tests
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make env=ci start;make env=ci wait-for-elastic;make env=ci xoff
    - name: DDD LAYERS
      run: make env=ci layer
    - name: DB Schema validation
      run: make env=ci schema-validate
    - name: CS
      run: make env=ci cs-check;make env=ci style;
      continue-on-error: true
    - name: Tests
      run: make env=ci xon;make env=ci conf="--coverage-clover build/logs/clover.xml" phpunit
    - name: ARTIFACT
      run: make env=ci artifact
    - name: Coveralls install
      run: wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar -O coveralls.phar;chmod +x coveralls.phar;
    - name: Coveralls report
      run: docker-compose exec -T php sh -lc "COVERALLS_RUN_LOCALLY=1 COVERALLS_EVENT_TYPE='manual' CI_NAME='php-coveralls' php coveralls.phar -v"
